### ISSUE TITLE
Is the V1.3 corresponding to the 'Nitrokey storage 2' product?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-storage-hardware#8]
If I understand correctly, there was a redesign of the "NK storage" product after the Cure53 audit, resulting in the "NK storage 2" product.

Does the NK storage v 1.3 on this repo corresponds to the "NK storage 2" product? If so, can this be made clearer? If not, can you point to the hardware repo for the "NK storage 2" product? :)

**Comment by jans23** [comment]
Yes, the NK Storage v 1.3 on this repo corresponds to the "NK Storage 2" product.
